### ISSUE TITLE
systemd version of udev places character device files in /dev/ instead of /dev/etherd/

### ISSUE THREAD

**Issue by ebolainfluenza** [OpenAoE/aoe#4] opened 2016-01-05 22:02 UTC
Expected Behavior:
Character device files discover, err, flush, interfaces, and revalidate are created in /dev/etherd/, not /dev/.
Aoetools commands that use these character device files work as expected.

Observed Behavior:
Character device files mounted in filesystem under /dev/, not /dev/etherd/.
Aoe-discover and aoe-flush commands fail with: /dev/etherd/^(discover flush) does not exist or is not writeable.

General Notes (ecashin to rtb email):
"This problem is familiar---We've encountered it before when udev's syntax changes.  The rules for creating the block device nodes is pretty simple, but the rules for the character device nodes are not as simple, so they break first.

In this case, the systemd version of udev that leary runs refuses to rename the device by prepending the "etherd/" to its name.  It does go ahead and create the character device files, but it does that right inside "/dev", not "/dev/etherd".

So we can add udev rules that create a symlink in "/dev/etherd" for platforms that don't support device renaming inside udev, or we could try to rename the character devices in the driver itself."

[sysinfo.txt](https://github.com/OpenAoE/aoe/files/79078/sysinfo.txt)

**Comment by ecashin** [comment] 2016-01-06 01:58
Thanks very much for the report.  I'm installing CentOS 7 now so that I have a throw-away system for experimentation.

**Comment by ecashin** [comment] 2016-01-08 02:26
Sir, would you mind please trying branch `v87pre2-etherd-chardev-names`?  After cloning this repo, you can do a `git checkout v87pre2-etherd-chardev-names` and build it.  After installation and module loading, `aoe-version` should confirm that you're running v87pre2s (with an "s" suffix).

The transcript below shows that it results in the expected behavior for the systemd-udev when it's ignoring the udev rule for character device files.  Even if this works, though, there are a lot of open questions, because of backwards compatibility.

Would you mind please finding out what Alyseo has done about this?  Usually they have RPMs that make the aoe driver work on major Linux distros, but I have to stop now and cannot check out whether they have CentOS 7 RPMs and what they did to the udev rules there.  They might have rewritten the rules to add symlinks.

```
...
+ install -m 700 aoe-sancheck /usr/sbin/aoe-sancheck
+ install -m 664 aoe-sancheck.8 /usr/share/man/man8/aoe-sancheck.8
make[1]: Leaving directory `/home/vagrant/aoe/aoetools-36'
[vagrant@localhost aoe]$ sudo modprobe aoe
[vagrant@localhost aoe]$ sudo aoe-version
              aoetools: 36
  installed aoe driver: 87pre2s
    running aoe driver: 87pre2s
[vagrant@localhost aoe]$ ls -l /dev/etherd
total 0
c-w--w----. 1 root disk 152, 3 Jan  7 21:18 discover
c-w--w----. 1 root disk 152, 2 Jan  7 21:18 err
c-w--w----. 1 root disk 152, 6 Jan  7 21:18 flush
c-w--w----. 1 root disk 152, 4 Jan  7 21:18 interfaces
c-w--w----. 1 root disk 152, 5 Jan  7 21:18 revalidate
[vagrant@localhost aoe]$ git branch
  master
* v87pre2-etherd-chardev-names
[vagrant@localhost aoe]$ 
```

**Comment by ebolainfluenza** [comment] 2016-01-11 02:23
No such luck on ftp://ftp.alyseo.com/.

**Comment by ecashin** [comment] 2016-01-14 01:55
Here's some good news: On CentOS 6.6, this experimental v87pre2s builds and installs without a hitch, and the character devices show up in /dev/etherd just as desired.

Even though the old style udev rules get installed, they don't match the new names.

I'd like to hear more about how this branch works for you on the varieties of Linux that you care about most, but so far this strategy for overcoming this issue looks good.

**Comment by ebolainfluenza** [comment] 2016-01-14 04:07
Will test it out on two or three different Linux flavors, then update here.  Thanks a bunch sir!

**Comment by nlmark** [comment] 2016-03-10 23:10
On Debian 8.3 this version (in v87pre2-etherd-chardev-names) works and the one in master doesn't work. Please let me know if I can help with a test on Debian when needed.

**Comment by ecashin** [comment] 2016-03-11 00:02
Hi! Can you tell whether the stock aoe driver (and not the from-source one)  from the debian kernel works for you when the aoetools are installed? 
On Mar 10, 2016 6:10 PM, nlmark notifications@github.com wrote:On Debian 8.3 this version (in v87pre2-etherd-chardev-names) works and the one in master doesn't work. Please let me know if I can help with a test on Debian when needed.

**Comment by ecashin** [comment] 2016-03-17 00:52
The fix in v87pre2-etherd-chardev-names was merged today.

**Closed as completed by ecashin** 2016-03-17 00:52 UTC
